

import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class ProjetoJava extends javax.swing.JFrame {
    
    Integer valor1, valor2, valor3, 
            maiorValorCpu = 0, menorValorCpu = 0, somaCpu = 0,
            maiorValorDisco = 0, menorValorDisco = 0, somaDisco = 0,
            maiorValorMemoria = 0, menorValorMemoria = 0, somaMemoria = 0,
            cliques = 0; 
    
    Double mediaCpu, mediaDisco, mediaMemoria;
    /**
     * Creates new form ProjetoJava
     */
    public ProjetoJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgbBarra1 = new javax.swing.JProgressBar();
        pgbBarra2 = new javax.swing.JProgressBar();
        pgbBarra3 = new javax.swing.JProgressBar();
        lbltext1 = new javax.swing.JLabel();
        lbltext2 = new javax.swing.JLabel();
        lbltext3 = new javax.swing.JLabel();
        lbltext5 = new javax.swing.JLabel();
        lbltext6 = new javax.swing.JLabel();
        lbltext4 = new javax.swing.JLabel();
        lbltext8 = new javax.swing.JLabel();
        lbltext9 = new javax.swing.JLabel();
        lbltext7 = new javax.swing.JLabel();
        lbltext11 = new javax.swing.JLabel();
        lbltext12 = new javax.swing.JLabel();
        lbltext10 = new javax.swing.JLabel();
        btnAcao = new javax.swing.JButton();
        lblValor1 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        lblValor3 = new javax.swing.JLabel();
        lblValor4 = new javax.swing.JLabel();
        lblValor5 = new javax.swing.JLabel();
        lblValor6 = new javax.swing.JLabel();
        lblValor7 = new javax.swing.JLabel();
        lblValor8 = new javax.swing.JLabel();
        lblValor9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltext1.setText("CPU:");

        lbltext2.setText("Disco:");

        lbltext3.setText("Memória:");

        lbltext5.setText("max:");

        lbltext6.setText("média:");

        lbltext4.setText("min:");

        lbltext8.setText("max:");

        lbltext9.setText("média:");

        lbltext7.setText("min:");

        lbltext11.setText("max:");

        lbltext12.setText("média:");

        lbltext10.setText("min:");

        btnAcao.setText("Fazer leitura dos dados");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        lblValor1.setText("0%");

        lblValor2.setText("0%");

        lblValor3.setText("0%");

        lblValor4.setText("0%");

        lblValor5.setText("0%");

        lblValor6.setText("0%");

        lblValor7.setText("0%");

        lblValor8.setText("0%");

        lblValor9.setText("0%");

        jLabel1.setText("Valor máximo:2,40GHz ");

        jLabel2.setText("Valor minímo: 0");

        jLabel3.setText("Valor máximo: 224 GB");

        jLabel4.setText("Valor minímo: 0");

        jLabel5.setText("Valor máximo: 7,9 GB");

        jLabel6.setText("Valor minímo: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pgbBarra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbltext1)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(pgbBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lbltext3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pgbBarra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lbltext2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltext4)
                            .addComponent(lblValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltext5)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbltext6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValor7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblValor8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltext12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValor9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltext10)
                                .addGap(35, 35, 35)
                                .addComponent(lbltext11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltext7)
                                    .addComponent(lblValor4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltext8)
                                    .addComponent(lblValor5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltext9)
                                    .addComponent(lblValor6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbltext1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbltext5)
                        .addComponent(lbltext4)
                        .addComponent(lbltext6))
                    .addComponent(pgbBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor1)
                            .addComponent(lblValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lbltext2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbltext7)
                        .addComponent(lbltext8)
                        .addComponent(lbltext9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblValor5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValor6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lbltext3)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pgbBarra3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltext10)
                            .addComponent(lbltext11)
                            .addComponent(lbltext12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblValor9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblValor8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        //adicionar cliques do botão
        cliques ++;
        
        //String para a porcentagem aparecer na média
        String porcentagem = "%";

                        
        //Gerar números aleatórios
        Random aleatorio1 = new Random();
        Random aleatorio2 = new Random();
        Random aleatorio3 = new Random();
        
        
        //Armazenei o valor sorteado em uma variável
        valor1 = aleatorio1.nextInt((100) +1);
        valor2 = aleatorio2.nextInt((100) +1);
        valor3 = aleatorio3.nextInt((100) +1);
        
        //Soma dos valores sorteados
        somaCpu += valor1;
        somaDisco += valor2;
        somaMemoria += valor3;
        
        //Média dos valores
        mediaCpu = (somaCpu.doubleValue() / cliques.doubleValue());
        mediaDisco = (somaDisco.doubleValue() / cliques.doubleValue());
        mediaMemoria = (somaMemoria.doubleValue() / cliques.doubleValue());
        
        //Mostrar progressão da barra
        pgbBarra1.setValue(valor1);
        pgbBarra2.setValue(valor2);
        pgbBarra3.setValue(valor3);
        
        //Mostrar valores da barra
        pgbBarra1.setStringPainted(true);
        pgbBarra2.setStringPainted(true);
        pgbBarra3.setStringPainted(true);
         
        
        //Vai exibir os valores minímos máximos e a média entre eles
        //Menor valor da CPU
        if(menorValorCpu == 0){
            menorValorCpu = valor1;                                         
        }
        if(valor1 < menorValorCpu){  
            menorValorCpu = valor1;           
            }
        lblValor1.setText(menorValorCpu + "%");
        
        //Maior valor da CPU
        if(maiorValorCpu == 0){
            maiorValorCpu = valor1;                                         
        }
        if(valor1 > maiorValorCpu){  
            maiorValorCpu = valor1;           
            } 
        lblValor2.setText(maiorValorCpu + "%");
        
        //Media valores sorteados da CPU
        lblValor3.setText(String.format("%.2f%s", mediaCpu, porcentagem));
        
         //Menor valor do Disco
        if(menorValorDisco == 0){
            menorValorDisco = valor2;                                         
        }
        if(valor2 < menorValorDisco){  
            menorValorDisco = valor2;           
            }
        lblValor4.setText(menorValorDisco + "%");
        
        //Maior valor do Disco
        if(maiorValorDisco == 0){
            maiorValorDisco = valor2;                                         
        }
        if(valor2 > maiorValorDisco){  
            maiorValorDisco = valor2;           
            } 
        lblValor5.setText(maiorValorDisco + "%");
        
        //Média valores sorteados do Disco
        lblValor6.setText(String.format("%.2f%s", mediaDisco, porcentagem));
        
          //Menor valor da Memória
        if(menorValorMemoria == 0){
            menorValorMemoria = valor3;                                         
        }
        if(valor3 < menorValorMemoria){  
            menorValorMemoria = valor3;           
            }
        lblValor7.setText(menorValorMemoria + "%");
        
        //Maior valor da Memória
        if(maiorValorMemoria == 0){
            maiorValorMemoria = valor3;                                         
        }
        if(valor3 > maiorValorMemoria){  
            maiorValorMemoria = valor3;           
            } 
        lblValor8.setText(maiorValorMemoria + "%");
        
        //Média valores sorteados da memória
        lblValor9.setText(String.format("%.2f%s", mediaMemoria, porcentagem));
    }//GEN-LAST:event_btnAcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JLabel lblValor4;
    private javax.swing.JLabel lblValor5;
    private javax.swing.JLabel lblValor6;
    private javax.swing.JLabel lblValor7;
    private javax.swing.JLabel lblValor8;
    private javax.swing.JLabel lblValor9;
    private javax.swing.JLabel lbltext1;
    private javax.swing.JLabel lbltext10;
    private javax.swing.JLabel lbltext11;
    private javax.swing.JLabel lbltext12;
    private javax.swing.JLabel lbltext2;
    private javax.swing.JLabel lbltext3;
    private javax.swing.JLabel lbltext4;
    private javax.swing.JLabel lbltext5;
    private javax.swing.JLabel lbltext6;
    private javax.swing.JLabel lbltext7;
    private javax.swing.JLabel lbltext8;
    private javax.swing.JLabel lbltext9;
    private javax.swing.JProgressBar pgbBarra1;
    private javax.swing.JProgressBar pgbBarra2;
    private javax.swing.JProgressBar pgbBarra3;
    // End of variables declaration//GEN-END:variables
}
